<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cp_authentication_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cp_authentication module.
    case 'help.page.cp_authentication':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Authentication module. Provide login form.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cp_authentication_theme($existing, $type, $theme, $path) {
  return [
    'cp_user_info_list' => [
      'variables' => [
        'items' => [],
      ],
      'file' => 'cp_authentication.field.inc'
    ],
  ];
}
